const samplelistings = [
    // Mountains
    {
        title: "Manali",
        description: "A beautiful hill station surrounded by snow-capped peaks.",
        image: "https://t4.ftcdn.net/jpg/01/96/02/01/240_F_196020123_gO0XJKP1zWkKjtLQeIRV05dGcIIlIeAo.jpg",
        Terrain: ["Mountain", "Snow"],
        location: "Himachal Pradesh",
        country: "India",
        rank: 1,
    },
    {
        title: "Leh-Ladakh",
        description: "A stunning region with breathtaking mountain landscapes and Buddhist monasteries.",
        image: "https://as1.ftcdn.net/v2/jpg/04/42/01/22/1000_F_442012259_YrX7LnvnZzFKZh97cpjcjhoeKFWemkUB.jpg",
        Terrain: ["Mountain"],
        location: "Ladakh",
        country: "India",
    },
    {
        title: "Auli",
        description: "Famous for its skiing slopes and stunning views.",
        image: "https://as2.ftcdn.net/v2/jpg/08/70/20/23/1000_F_870202396_Ft8QSF57bBARXgyyi51jQ3CSDQbjQkBW.jpg",
        Terrain: ["Mountain", "Snow"],
        location: "Uttarakhand",
        country: "India",
        rank: 4,
    },
    {
        title: "Kodaikanal",
        description: "A serene hill station known for its beautiful lakes and pleasant climate.",
        image: "https://as1.ftcdn.net/v2/jpg/07/62/90/00/1000_F_762900048_sSG3xLlyJnKfIcAByfg3h9GMU5GLoSDV.jpg",
        Terrain: ["Mountain"],
        location: "Tamil Nadu",
        country: "India",
    },
    {
        title: "Nainital",
        description: "A picturesque hill station set around a beautiful lake, surrounded by mountains.",
        image: "https://as2.ftcdn.net/v2/jpg/05/75/39/87/1000_F_575398724_o8AvQUcSIKzItf4yI7k7sQn07dex90IF.jpg",
        Terrain: ["Mountain", "Snow"],
        location: "Uttarakhand",
        country: "India",
    },
    {
        title: "Gulmarg",
        description: "A popular ski resort known for its breathtaking snow-covered landscapes.",
        image: "https://as2.ftcdn.net/v2/jpg/07/93/89/01/1000_F_793890131_ibPu3HhMetqGccIuxu6FpB5KmvdzGKbD.jpg",
        Terrain: ["Mountain", "Snow"],
        location: "Jammu and Kashmir",
        country: "India",
        rank: 2,
    },
    {
        title: "Darjeeling",
        description: "Known for its tea plantations and stunning views of the Himalayas.",
        image: "https://as2.ftcdn.net/v2/jpg/02/57/98/85/1000_F_257988556_UbxCEwXDBjknhWhNAYmY3wuxnRHxz1vK.jpg",
        Terrain: ["Mountain"],
        location: "West Bengal",
        country: "India",
    },
    {
        title: "Coorg",
        description: "Known for its lush greenery and coffee plantations, a beautiful hill station.",
        image: "https://as1.ftcdn.net/v2/jpg/00/92/34/50/1000_F_92345026_TIFAv9VVGkK4rnMBhLSidN52XGzBQkwj.jpg",
        Terrain: ["Mountain"],
        location: "Karnataka",
        country: "India",
    },
    {
        title: "Horsley Hills",
        description: "A serene hill station known for its cool climate and scenic beauty.",
        image: "https://www.holidify.com/images/cmsuploads/compressed/HorsleyHillstrek_20200507184008.jpg",
        Terrain: ["Mountain"],
        location: "Andhra Pradesh",
        country: "India",
    },
    {
        title: "Araku Valley",
        description: "A picturesque valley known for its lush green landscapes and coffee plantations.",
        image: "https://as1.ftcdn.net/v2/jpg/02/05/37/76/1000_F_205377656_RJbSY9WZXsA3YO88akDBtnQTVLsIKzjb.jpg",
        Terrain: ["Mountain"],
        location: "Andhra Pradesh",
        country: "India",
        rank: 8,
    },

    // Beaches
    {
        title: "Goa",
        description: "Famous for its stunning beaches and vibrant nightlife.",
        image: "https://as1.ftcdn.net/v2/jpg/00/77/00/26/1000_F_77002615_Gl1Hk6qZpi2xCAlX8EUTRLBqC4ei6QfC.jpg",
        Terrain: ["Beach"],
        location: "Goa",
        country: "India",
        rank: 3,
    },
    {
        title: "Andaman and Nicobar Islands",
        description: "Known for its pristine beaches and crystal-clear waters.",
        image: "https://as1.ftcdn.net/v2/jpg/03/27/49/04/1000_F_327490432_E0Ve4FMjC6kjCex350CsaMItt92JKnxP.jpg",
        Terrain: ["Beach"],
        location: "Andaman and Nicobar Islands",
        country: "India",
    },
    {
        title: "Marari Beach",
        description: "A serene beach known for its tranquility and natural beauty.",
        image: "https://as1.ftcdn.net/v2/jpg/04/25/87/68/1000_F_425876819_r9xXDIAI02vr6rlR6BYeod9yMyUej2IQ.jpg",
        Terrain: ["Beach"],
        location: "Kerala",
        country: "India",
    },
    {
        title: "Varkala Beach",
        description: "Known for its cliffs and natural springs, a popular beach destination.",
        image: "https://as1.ftcdn.net/v2/jpg/08/76/20/42/1000_F_876204259_yKPrEfECZaSbWYex73kf72deWwprw04y.jpg",
        Terrain: ["Beach"],
        location: "Kerala",
        country: "India",
    },
    {
        title: "Puri",
        description: "Famous for its beach and the annual Rath Yatra festival.",
        image: "https://as1.ftcdn.net/v2/jpg/06/73/29/90/1000_F_673299077_JH6tAWLSRRuo4xcKaFUACmu8qtrY91hc.jpg",
        Terrain: ["Beach"],
        location: "Odisha",
        country: "India",
    },
    {
        title: "Kovalam",
        description: "A popular beach destination known for its lighthouses and resorts.",
        image: "https://as2.ftcdn.net/v2/jpg/01/03/86/23/1000_F_103862339_cOfXZoaAkgfcJ2l4LfVfshucKw09AIBd.jpg",
        Terrain: ["Beach"],
        location: "Kerala",
        country: "India",
    },
    {
        title: "Juhu Beach",
        description: "A famous beach in Mumbai, known for its vibrant atmosphere and street food.",
        image: "https://as2.ftcdn.net/v2/jpg/02/68/97/51/1000_F_268975159_y2qkqGapj4YF9KdDKYtLtI0ojk5WzcKo.jpg",
        Terrain: ["Beach"],
        location: "Maharashtra",
        country: "India",
    },
    {
        title: "Alleppey Beach",
        description: "Known for its backwaters and beautiful beach, perfect for relaxation.",
        image: "https://as1.ftcdn.net/v2/jpg/07/28/44/30/1000_F_728443098_a2B36OYVi96gqGU7o9j6jN3CWdMw8Vj5.jpg",
        Terrain: ["Beach"],
        location: "Kerala",
        country: "India",
    },
    {
        title: "Marina Beach",
        description: "One of the longest urban beaches in the world, located in Chennai.",
        image: "https://as2.ftcdn.net/v2/jpg/04/84/47/27/1000_F_484472702_acpl3SZTBwb2Al4ZiW8VusICp7Utl8ed.jpg",
        Terrain: ["Beach"],
        location: "Tamil Nadu",
        country: "India",
    },
    {
        title: "Ramakrishna Beach",
        description: "A popular beach in Visakhapatnam, known for its beauty and activities.",
        image: "https://t4.ftcdn.net/jpg/06/65/95/63/240_F_665956351_DJYCz1bG9QYsqG9NAgUE6r4NltzmLATP.jpg",
        Terrain: ["Beach"],
        location: "Andhra Pradesh",
        country: "India",
    },

    // Snowy Places
    {
        title: "Auli",
        description: "Famous for its skiing slopes and stunning views.",
        image: "https://t3.ftcdn.net/jpg/06/16/49/30/240_F_616493005_GAn9fGMFk3YcDTZWWB3uk4M00owII1ds.jpg",
        Terrain: ["Snow"],
        location: "Uttarakhand",
        country: "India",
        rank: 4,
    },
    {
        title: "Gulmarg",
        description: "A popular ski resort known for its breathtaking snow-covered landscapes.",
        image: "https://t4.ftcdn.net/jpg/04/38/03/87/240_F_438038733_JLqp2mWxSBFmBUicX4nD1ErCu0ydG9YQ.jpg",
        Terrain: ["Snow"],
        location: "Jammu and Kashmir",
        country: "India",
    },
    {
        title: "Kufri",
        description: "A small hill station famous for its snow activities.",
        image: "https://as2.ftcdn.net/v2/jpg/03/47/20/11/1000_F_347201177_FUccBvfY9pOFJAdDinDN8955YagQNlmS.jpg",
        Terrain: ["Snow"],
        location: "Himachal Pradesh",
        country: "India",
    },
    {
        title: "Nainital",
        description: "A picturesque hill station set around a beautiful lake, often covered in snow.",
        image: "https://t3.ftcdn.net/jpg/03/68/81/60/240_F_368816008_Ch4omKXQBapzQVEzC0urWVyDUXYfVXwY.jpg",
        Terrain: ["Snow"],
        location: "Uttarakhand",
        country: "India",
    },
    {
        title: "Chopta",
        description: "Known as the 'Mini Switzerland of India,' a beautiful snow-covered landscape.",
        image: "https://t4.ftcdn.net/jpg/03/92/76/85/240_F_392768583_Rj3mgA7pkDU9UsFRfsLeTKmTZy4C5dTN.jpg",
        Terrain: ["Snow"],
        location: "Uttarakhand",
        country: "India",
    },
    {
        title: "Pahalgam",
        description: "A beautiful valley often blanketed with snow in winter.",
        image: "https://t4.ftcdn.net/jpg/07/93/88/81/240_F_793888141_M0yziUMqqV9JFz6O1beQ3pgYzAzV2KXq.jpg",
        Terrain: ["Snow"],
        location: "Jammu and Kashmir",
        country: "India",
    },
    {
        title: "Rohtang Pass",
        description: "Famous for its breathtaking views and snow-covered terrain.",
        image: "https://t4.ftcdn.net/jpg/03/94/77/25/240_F_394772540_YOslG04YFbiekRcxGNuKbIq0VqajSxPr.jpg",
        Terrain: ["Snow"],
        location: "Himachal Pradesh",
        country: "India",
    },
    {
        title: "Shimla",
        description: "The capital of Himachal Pradesh, known for its colonial architecture and snowfall.",
        image: "https://as1.ftcdn.net/v2/jpg/04/34/02/68/1000_F_434026829_Mk7Nvf43x6UQNW7LDDyiEZeExr6FOitb.jpg",
        Terrain: ["Snow"],
        location: "Himachal Pradesh",
        country: "India",
    },

    // Deserts
    {
        title: "Thar Desert",
        description: "A vast desert known for its unique landscapes and rich cultural heritage.",
        image: "https://t4.ftcdn.net/jpg/09/79/80/13/240_F_979801301_1mZ70k0gMJccO7WRS9nF2zAg5oZ5PAYD.jpg",
        Terrain: ["Desert"],
        location: "Rajasthan",
        country: "India",
    },
    {
        title: "Rann of Kutch",
        description: "A unique salt desert known for its stunning landscapes and cultural experiences.",
        image: "https://t3.ftcdn.net/jpg/01/44/50/40/240_F_144504004_4EDjT8kQeUJHGqJ6Uz0m6fttfRoULHRF.jpg",
        Terrain: ["Desert"],
        location: "Gujarat",
        country: "India",
    },
    {
        title: "Kutch Desert",
        description: "Famous for its white salt desert, a picturesque landscape.",
        image: "https://t3.ftcdn.net/jpg/04/42/97/68/240_F_442976845_vVNsnuN125yAPg1URBfWEM714vAk9MZG.jpg",
        Terrain: ["Desert"],
        location: "Gujarat",
        country: "India",
    },
    {
        title: "Deccan Plateau",
        description: "A large plateau with unique geological features and landscapes.",
        image: "https://t4.ftcdn.net/jpg/01/82/67/55/240_F_182675545_I13lDKlaRWaafN386EWEh1XapgI1ZdKh.jpg",
        Terrain: ["Desert"],
        location: "Telangana",
        country: "India",
    },
    {
        title: "Little Rann of Kutch",
        description: "Known for its wildlife and unique landscapes.",
        image: "https://as2.ftcdn.net/v2/jpg/03/04/62/29/1000_F_304622987_XDlwpUiji6eMiMclSycbfjobbGVudGq1.jpg",
        Terrain: ["Desert"],
        location: "Gujarat",
        country: "India",
    },

    // Mysterious Places
    {
        title: "Jatinga",
        description: "A small village famous for mysterious bird suicides.",
        image: "https://travelsetu.com/apps/uploads/new_destinations_photos/destination/2023/12/20/a8c2dd22833c3ef4b279d5ccaef29174_1000x1000.jpg",
        Terrain: ["Mysterious"],
        location: "Assam",
        country: "India",
        rank: 6,
    },
    {
        title: "Shani Shingnapur",
        description: "A village where houses have no doors, believed to be protected by a deity.",
        image: "https://indroyc.com/wp-content/uploads/2012/08/shani-mandir.jpg?w=750",
        Terrain: ["Mysterious"],
        location: "Maharashtra",
        country: "India",
    },
    {
        title: "Bhangarh Fort",
        description: "An ancient fort known as one of the most haunted places in India.",
        image: "https://t3.ftcdn.net/jpg/03/00/61/62/240_F_300616253_wN0qhZsfuCjOeFCO8hsPyNnGO7EaG3h2.jpg",
        Terrain: ["Mysterious", "Horror"],
        location: "Rajasthan",
        country: "India",
        rank: 5,
    },
    {
        title: "Kuldhara",
        description: "An abandoned village with a mysterious history and folklore.",
        image: "https://t4.ftcdn.net/jpg/04/64/11/57/240_F_464115736_9vXdsyPShBTORVDzgE9EOhZF598fmmzm.jpg",
        Terrain: ["Mysterious"],
        location: "Rajasthan",
        country: "India",
    },
    {
        title: "Nanda Devi",
        description: "Known for mysterious disappearances and spiritual significance.",
        image: "https://upload.wikimedia.org/wikipedia/commons/d/d2/Mt._Nanda_Devi.jpg",
        Terrain: ["Mysterious"],
        location: "Uttarakhand",
        country: "India",
    },
    {
        title: "Kashmir Valley",
        description: "A beautiful valley shrouded in legends and mysteries.",
        image: "https://t3.ftcdn.net/jpg/09/99/88/98/240_F_999889807_aIW2Yq3CwJref34jaYCUfz6o6aqJfOSK.jpg",
        Terrain: ["Mysterious"],
        location: "Jammu and Kashmir",
        country: "India",
    },
    {
        title: "Lepakshi",
        description: "Known for its ancient temples and legends of its origins.",
        image: "https://t4.ftcdn.net/jpg/01/44/54/09/240_F_144540947_yorhjNaBlWwl6KL7w0auZ5QNEsXt6Uku.jpg",
        Terrain: ["Mysterious"],
        location: "Andhra Pradesh",
        country: "India",
        rank: 10,
    },
    {
        title: "Vijayawada Caves",
        description: "Mysterious caves with ancient carvings and legends.",
        image: "https://t3.ftcdn.net/jpg/03/07/69/50/240_F_307695094_VW093ecv3jel4Xr27wkAj4hyWjApCO5Y.jpg",
        Terrain: ["Mysterious"],
        location: "Andhra Pradesh",
        country: "India",
    },
    {
        title: "Hampi",
        description: "A UNESCO World Heritage site known for its ancient ruins and history.",
        image: "https://t3.ftcdn.net/jpg/05/90/43/16/240_F_590431642_1IKsCZFmSIzw8fNukgwXWMH9JxPBeZ2w.jpg",
        Terrain: ["Mysterious"],
        location: "Karnataka",
        country: "India",
        rank: 9,
    },
    {
        title: "Ananthagiri Hills",
        description: "A hill station known for its mysterious beauty and legends.",
        image: "https://t3.ftcdn.net/jpg/01/30/41/60/240_F_130416011_PsqQuNIagFSS8dzLbptKWcf5ReOtoul3.jpg",
        Terrain: ["Mysterious"],
        location: "Telangana",
        country: "India",
    },

    // Horror Places
    {
        
        title: "Bhangarh Fort",
        description: "An ancient fort known as one of the most haunted places in India.",
        image: "https://t3.ftcdn.net/jpg/02/84/53/86/240_F_284538613_pjoU2UOAs2GDsBCCFAATLUj2PKrnKrpz.jpg",
        Terrain: ["Horror", "Mysterious"],
        location: "Rajasthan",
        country: "India",
        rank: 5,
    },
    {
        title: "Shaniwar Peth",
        description: "A locality known for ghost stories and haunted sites.",
        image: "https://im.whatshot.in/img/2021/Feb/156677-c-1614196057.jpg",
        Terrain: ["Horror"],
        location: "Maharashtra",
        country: "India",
    },
    {
        title: "Dow Hill",
        description: "Famous for ghost sightings and eerie stories.",
        image: "https://t4.ftcdn.net/jpg/03/73/39/11/240_F_373391121_wemrBHzQ3iR2YelttXn6752uzdkyIgA5.jpg",
        Terrain: ["Horror"],
        location: "West Bengal",
        country: "India",
    },
    {
        title: "Kuldhara",
        description: "An abandoned village with a mysterious history and folklore.",
        image: "https://t3.ftcdn.net/jpg/01/16/77/08/240_F_116770865_GDSnxegipBmSmDeKVYZfwYzBnhxOkLVr.jpg",
        Terrain: ["Horror", "Mysterious"],
        location: "Rajasthan",
        country: "India",
    },
    {
        title: "Jatinga",
        description: "A small village famous for mysterious bird suicides.",
        image: "https://travelsetu.com/apps/uploads/new_destinations_photos/destination/2023/12/20/a8c2dd22833c3ef4b279d5ccaef29174_1000x1000.jpg",
        Terrain: ["Horror", "Mysterious"],
        location: "Assam",
        country: "India",
    },
    {
        title: "Kumarakom",
        description: "Known for eerie experiences and ghost stories.",
        image: "https://t4.ftcdn.net/jpg/00/92/88/57/240_F_92885790_DL6VCDswNG9JwkzOGXWi0r0qipXXdAJg.jpg",
        Terrain: ["Horror"],
        location: "Kerala",
        country: "India",
    },
    {
        title: "Tawang Monastery",
        description: "A historic monastery with spooky legends.",
        image: "https://footloosedev.com/wp-content/uploads/2016/01/Tawang-monastery-2-e1477123341974.jpg",
        Terrain: ["Horror"],
        location: "Arunachal Pradesh",
        country: "India",
    },
    {
        title: "Jaisalmer Fort",
        description: "An ancient fort with tales of hauntings and ghost stories.",
        image: "https://t4.ftcdn.net/jpg/07/13/86/75/240_F_713867584_XLAYNyKNRwE81dEjKoY09YighQVRXoRO.jpg",
        Terrain: ["Horror"],
        location: "Rajasthan",
        country: "India",
    },
    {
        title: "Savoy Hotel",
        description: "A haunted hotel with eerie tales of spirits.",
        image: "https://t3.ftcdn.net/jpg/09/74/78/72/240_F_974787217_ynS0jAQGnB0QIyJJcAephIXRJ5xcn27t.jpg",
        Terrain: ["Horror"],
        location: "Uttarakhand",
        country: "India",
    },
];

module.exports = {data : samplelistings};
